### ISSUE TITLE
Add an extra docker-compose intermediate step

### ISSUE THREAD

**Issue by nimpo** [UoMResearchIT/docker-introduction#100]
When adding build to the docked compose. I suggest perhaps showing how one might use the new image built in the previous steps via the image keyword thus:
What was:
```
services:
  spuc:
    image: spuacv/spuc:latest
...
    volumes:
    ...
      - ./stats.py:/spuc/plugins/stats.py
```
which fails as the stats.py requires pandas. 
Do this as the next step first, using what we just learned:
```
services:
  spuc:
    image: spuc-stats
```
then move onto.
```
services:
  spuc:
    build:
      context: .
      dockerfile: Dockerfile
```

Then replace that with the build: tag.

----
NB
```
  build:
    context: .
    dockerfile: Dockerfile
```
is equivalent to 
```
  build: .
```
