### ISSUE TITLE
Missing volumes declaration in docker compose file

### ISSUE THREAD

**Issue by Josh-Woodcock** [UoMResearchIT/docker-introduction#113]
the `volumes` are not specified at in the docker-compose.yml snippet. It tripped me up as I was copying and pasting the changes rather than doing it manually.

See - https://uomresearchit.github.io/docker-introduction/docker-compose.html#building-containers-in-docker-compose

it should be - 

```

services:
  spuc:
  # image: spuacv/spuc:latest
    build:                        # Instead of using the 'image' key, we use the 'build' key
      context: .                  # Sets the build context (the directory in which the Dockerfile is located)
      dockerfile: Dockerfile      # Sets the name of the Dockerfile
    container_name: spuc_container
    ports:
      - 8321:8321
    volumes:
      - ./print.config:/spuc/config/print.config
      - spuc-volume:/spuc/output
      - ./stats.py:/spuc/plugins/stats.py
    environment:
      - EXPORT=true
    command: ["--units", "iulu"]

volumes:
  spuc-volume:

```
